services:
  backend:
    image: reader-inquisitor/backend
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    env_file:
      - backend.env
    ports:
      - 3000:3000
      - 4000:4000
    command: npm run start
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  discord:
    image: reader-inquisitor/discord
    build:
      context: ../..
      dockerfile: infra/docker/discord.Dockerfile
    env_file:
      - discord.env
    ports:
      - 3003:3003
    command: npm run start
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  bot:
    image: reader-inquisitor/bot
    build:
      context: ../..
      dockerfile: infra/docker/bot.Dockerfile
    env_file:
      - bot.env
    ports:
      - 3002:3002
    command: npm run start
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  frontend:
    image: reader-inquisitor/frontend
    build:
      context: ../..
      dockerfile: infra/docker/frontend.Dockerfile
    ports:
      - 1234:1234
    command: npm run start
    env_file:
      - frontend.env
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  database:
    image: reader-inquisitor/database
    build:
      context: ../..
      dockerfile: infra/docker/database.Dockerfile
    env_file:
      - database.env
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3001:3306
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s

volumes:
  database_data: