apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  type: NodePort
  selector:
    app: reader-inquisitor
    service: discord
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30002