apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
spec:
  template:
    spec:
      containers:
      - name: discord
        env:
        - name: BACKEND_URL
          value: "http://prod-backend-backdoor:4000"
